### ISSUE TITLE
Apex jar file not relocatable

### ISSUE THREAD

**Issue by doctorfree** [igorcguedes/SaleVim#1]
The path to the apex jar file in `lua/user/lsp/mason.lua` is hardcoded to the user's home directory `/.config/nvim/lspserver/`

Beginning with Neovim 0.9 the environment variable `NVIM_APPNAME` can be used to specify an alternate directory for the Neovim configuration making Neovim configs relocatable. To make your configuration relocatable, replace the line:

```lua
local apex_jar_path = '/home/' .. username .. '/.config/nvim/lspserver/' .. apex_jar_filename
```

with something like:

```lua
local apex_jar_path = vim.fn.stdpath("config") .. '/lspserver/' .. apex_jar_filename
```

**Comment by igorcguedes** [comment]
Great upgrade! This change has been implemented and committed. Thank you for the suggestion.

**Comment by doctorfree** [comment]
Nice response time!

I plan to add `SaleVim` to the [Lazyman Configuration Manager](https://github.com/doctorfree/nvim-lazyman) later today if that's ok with you.

Note: the current Neovim stable release version is `0.9` rather than `9.0` in the README requirements.

Nice config. I am a fan of targeted use case configurations.

**Comment by igorcguedes** [comment]
I would love to! This will make it much more dynamic and adaptable. True, I didn't even notice that I reversed the 9.0, haha. Thank you, I fixed it there.
Waiting to test it.

**Comment by doctorfree** [comment]
`SaleVim` has been added to [Lazyman](https://github.com/doctorfree/nvim-lazyman) as one of the `Custom` configurations. It can be installed and initialized using the `lazyman` command with:

```bash
lazyman -C https://github.com/igorcguedes/SaleVim -N nvim-SaleVim -P
```

It can also be installed and initialized using the Lazyman Menu system.

Please let me know if you have any feedback, suggestions, criticism, or requests for how `SaleVim` is described, installed, initialized, or otherwise used by Lazyman. I plan to do further integration as I have time and always welcome suggestions.

Nice work!

**Comment by igorcguedes** [comment]
I apologize for the delayed response. I was busy working on developing new features for SaleVim. During that time, I had the opportunity to test and work with Lazyman, and it proved to be extremely helpful. The ability to configure different settings with such ease was truly awesome. In the near future, I plan to recommend trying out SaleVim alongside Lazyman.

Nice work too!!

**Comment by doctorfree** [comment]
Thank you! Just to be clear, the ability to configure different settings in the Lazyman menus only applies to the Lazyman Neovim configuration in `~/.config/nvim-Lazyman`. The other Neovim configurations that `lazyman` installs and initializes, such as `SaleVim`, each have their own manual configuration method.

The `lazyman` command has a main menu for managing all the supported Neovim configurations but it also has sub-menus to configure the `nvim-Lazyman` Neovim configuration. I suppose I should have made that a bit more clear.

Hope you were not confused by this. If you want to make `SaleVim` configurable in the same manner then examine the configuration in `~/.config/nvim-Lazyman/` especially the file `~/.config/nvim-Lazyman/lua/configuration.lua` where I store all the menu configurable settings for that config. Then in the plugins configuration and other settings files there is a `local settings = require("configuration")` which is then used to dynamically configure.

Hopefully this clarifies the configuration menu system for you if you were under the impression that it could be used to configure `SaleVim`. Sorry!
